// <auto-generated />
using System;
using Gestao_Loja.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoLoja.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestao_Loja.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apelido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoConta")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoConta")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Gestao_Loja.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoCategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.HasIndex("TipoCategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Nome = "Filme",
                            TipoCategoriaId = 1
                        },
                        new
                        {
                            CategoriaId = 2,
                            Nome = "Música",
                            TipoCategoriaId = 1
                        },
                        new
                        {
                            CategoriaId = 3,
                            Nome = "Jogo",
                            TipoCategoriaId = 1
                        },
                        new
                        {
                            CategoriaId = 4,
                            Nome = "Série",
                            TipoCategoriaId = 1
                        },
                        new
                        {
                            CategoriaId = 5,
                            Nome = "Sony",
                            TipoCategoriaId = 2
                        },
                        new
                        {
                            CategoriaId = 6,
                            Nome = "Warner",
                            TipoCategoriaId = 2
                        },
                        new
                        {
                            CategoriaId = 7,
                            Nome = "Universal",
                            TipoCategoriaId = 2
                        },
                        new
                        {
                            CategoriaId = 8,
                            Nome = "EA Games",
                            TipoCategoriaId = 2
                        },
                        new
                        {
                            CategoriaId = 9,
                            Nome = "Metallica",
                            TipoCategoriaId = 3
                        },
                        new
                        {
                            CategoriaId = 10,
                            Nome = "Queen",
                            TipoCategoriaId = 3
                        },
                        new
                        {
                            CategoriaId = 11,
                            Nome = "Eminem",
                            TipoCategoriaId = 3
                        },
                        new
                        {
                            CategoriaId = 12,
                            Nome = "Coldplay",
                            TipoCategoriaId = 3
                        },
                        new
                        {
                            CategoriaId = 13,
                            Nome = "Ação",
                            TipoCategoriaId = 4
                        },
                        new
                        {
                            CategoriaId = 14,
                            Nome = "Drama",
                            TipoCategoriaId = 4
                        },
                        new
                        {
                            CategoriaId = 15,
                            Nome = "Rock",
                            TipoCategoriaId = 4
                        },
                        new
                        {
                            CategoriaId = 16,
                            Nome = "Pop",
                            TipoCategoriaId = 4
                        },
                        new
                        {
                            CategoriaId = 17,
                            Nome = "RAP",
                            TipoCategoriaId = 4
                        },
                        new
                        {
                            CategoriaId = 18,
                            Nome = "PS5",
                            TipoCategoriaId = 5
                        },
                        new
                        {
                            CategoriaId = 19,
                            Nome = "Xbox",
                            TipoCategoriaId = 5
                        },
                        new
                        {
                            CategoriaId = 20,
                            Nome = "PC",
                            TipoCategoriaId = 5
                        },
                        new
                        {
                            CategoriaId = 21,
                            Nome = "Nintendo Switch",
                            TipoCategoriaId = 5
                        });
                });

            modelBuilder.Entity("Gestao_Loja.Entities.CategoriaProduto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("CategoriaProdutos");
                });

            modelBuilder.Entity("Gestao_Loja.Entities.LinhaVenda", b =>
                {
                    b.Property<int>("LinhaVendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinhaVendaId"));

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalLinha")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("LinhaVendaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("LinhasVenda");
                });

            modelBuilder.Entity("Gestao_Loja.Entities.ModoDisponibilizacao", b =>
                {
                    b.Property<int>("ModoDisponibilizacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModoDisponibilizacaoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModoDisponibilizacaoId");

                    b.ToTable("ModosDisponibilizacao");

                    b.HasData(
                        new
                        {
                            ModoDisponibilizacaoId = 1,
                            Ativo = true,
                            IsForSale = true,
                            Nome = "Para Venda"
                        },
                        new
                        {
                            ModoDisponibilizacaoId = 2,
                            Ativo = true,
                            IsForSale = false,
                            Nome = "Para Listagem"
                        },
                        new
                        {
                            ModoDisponibilizacaoId = 3,
                            Ativo = true,
                            IsForSale = true,
                            Nome = "Pré-Venda"
                        },
                        new
                        {
                            ModoDisponibilizacaoId = 4,
                            Ativo = true,
                            IsForSale = false,
                            Nome = "Esgotado"
                        },
                        new
                        {
                            ModoDisponibilizacaoId = 5,
                            Ativo = false,
                            IsForSale = false,
                            Nome = "Interno"
                        });
                });

            modelBuilder.Entity("Gestao_Loja.Entities.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ModoDisponibilizacaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PercentagemComissao")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrecoFinal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProdutoId");

                    b.HasIndex("ModoDisponibilizacaoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Gestao_Loja.Entities.TipoCategoria", b =>
                {
                    b.Property<int>("TipoCategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoCategoriaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoCategoriaId");

                    b.ToTable("TipoCategorias");

                    b.HasData(
                        new
                        {
                            TipoCategoriaId = 1,
                            Nome = "Tipo"
                        },
                        new
                        {
                            TipoCategoriaId = 2,
                            Nome = "Editora"
                        },
                        new
                        {
                            TipoCategoriaId = 3,
                            Nome = "Grupo"
                        },
                        new
                        {
                            TipoCategoriaId = 4,
                            Nome = "Género"
                        },
                        new
                        {
                            TipoCategoriaId = 5,
                            Nome = "Plataforma"
                        });
                });

            modelBuilder.Entity("Gestao_Loja.Entities.Venda", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaId"));

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExpedicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPagamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("PagamentoExecutado")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VendaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Gestao_Loja.Entities.Categoria", b =>
                {
                    b.HasOne("Gestao_Loja.Entities.TipoCategoria", "TipoCategoria")
                        .WithMany("Categorias")
                        .HasForeignKey("TipoCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoCategoria");
                });

            modelBuilder.Entity("Gestao_Loja.Entities.CategoriaProduto", b =>
                {
                    b.HasOne("Gestao_Loja.Entities.Categoria", "Categoria")
                        .WithMany("CategoriaProdutos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestao_Loja.Entities.Produto", "Produto")
                        .WithMany("CategoriaProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Gestao_Loja.Entities.LinhaVenda", b =>
                {
                    b.HasOne("Gestao_Loja.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestao_Loja.Entities.Venda", "Venda")
                        .WithMany("Linhas")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Gestao_Loja.Entities.Produto", b =>
                {
                    b.HasOne("Gestao_Loja.Entities.ModoDisponibilizacao", "ModoDisponibilizacao")
                        .WithMany("Produtos")
                        .HasForeignKey("ModoDisponibilizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModoDisponibilizacao");
                });

            modelBuilder.Entity("Gestao_Loja.Entities.Venda", b =>
                {
                    b.HasOne("Gestao_Loja.Data.ApplicationUser", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Gestao_Loja.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Gestao_Loja.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestao_Loja.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Gestao_Loja.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestao_Loja.Entities.Categoria", b =>
                {
                    b.Navigation("CategoriaProdutos");
                });

            modelBuilder.Entity("Gestao_Loja.Entities.ModoDisponibilizacao", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Gestao_Loja.Entities.Produto", b =>
                {
                    b.Navigation("CategoriaProdutos");
                });

            modelBuilder.Entity("Gestao_Loja.Entities.TipoCategoria", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("Gestao_Loja.Entities.Venda", b =>
                {
                    b.Navigation("Linhas");
                });
#pragma warning restore 612, 618
        }
    }
}
